# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteAsignacionCarreraPeriodo',
            fields=[
                ('id_asignacion_carrera_periodo', models.BigAutoField(db_column='id_asignacion_carrera_periodo', primary_key=True, serialize=False)),
                ('horas_otras_unidades_academicas', models.IntegerField(db_column='horas_otras_unidades_academicas', default=0)),
                ('observacion_periodo', models.TextField(blank=True, db_column='observacion_periodo', null=True)),
            ],
            options={
                'verbose_name': 'Asignación Docente → Carrera/Período',
                'verbose_name_plural': 'M2 · Docentes · Asignaciones Carrera/Período',
                'db_table': 'docente_asignacion_carrera_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteCampoAfinidad',
            fields=[
                ('id_docente_campo', models.BigAutoField(db_column='id_docente_campo', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Campo Afinidad (Docente)',
                'verbose_name_plural': 'M2 · Docentes · Campos Afinidad',
                'db_table': 'docente_campo_afinidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteCursoCapacitacion',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('nombre_curso_capacitacion', models.CharField(db_column='nombre_curso_capacitacion', max_length=200)),
                ('fecha_inicio_curso', models.DateField(blank=True, db_column='fecha_inicio_curso', null=True)),
                ('fecha_fin_curso', models.DateField(blank=True, db_column='fecha_fin_curso', null=True)),
                ('horas_totales_curso', models.SmallIntegerField(db_column='horas_totales_curso', default=0)),
            ],
            options={
                'verbose_name': 'Curso de Capacitación',
                'verbose_name_plural': 'M2 · Docentes · Cursos Capacitación',
                'db_table': 'docente_curso_capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteFcacc',
            fields=[
                ('id_docente', models.BigAutoField(db_column='id_docente', primary_key=True, serialize=False)),
                ('cedula_docente', models.CharField(db_column='cedula_docente', max_length=13, unique=True)),
                ('nombres_completos', models.CharField(db_column='nombres_completos', max_length=200)),
                ('unidad_organica', models.CharField(blank=True, db_column='unidad_organica', max_length=100, null=True)),
                ('correo_institucional', models.EmailField(blank=True, db_column='correo_institucional', max_length=100, null=True, unique=True)),
                ('numero_celular', models.CharField(blank=True, db_column='numero_celular', max_length=15, null=True)),
                ('tipo_sangre', models.CharField(blank=True, db_column='tipo_sangre', max_length=5, null=True)),
                ('docente_activo', models.BooleanField(db_column='docente_activo', default=True)),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion_registro')),
            ],
            options={
                'verbose_name': 'Docente (FCACC)',
                'verbose_name_plural': 'M2 · Docentes',
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteParticipacionCurso',
            fields=[
                ('id_participacion', models.BigAutoField(db_column='id_participacion', primary_key=True, serialize=False)),
                ('fecha_participacion', models.DateField(db_column='fecha_participacion')),
            ],
            options={
                'verbose_name': 'Participación en Curso',
                'verbose_name_plural': 'M2 · Docentes · Participaciones en Cursos',
                'db_table': 'docente_participacion_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocentePublicacionAcademica',
            fields=[
                ('id_publicacion', models.BigAutoField(db_column='id_publicacion', primary_key=True, serialize=False)),
                ('nombre_publicacion', models.CharField(db_column='nombre_publicacion', max_length=200)),
                ('fecha_publicacion', models.DateField(blank=True, db_column='fecha_publicacion', null=True)),
                ('detalle_publicacion', models.TextField(blank=True, db_column='detalle_publicacion', null=True)),
            ],
            options={
                'verbose_name': 'Publicación Académica (Docente)',
                'verbose_name_plural': 'M2 · Docentes · Publicaciones Académicas',
                'db_table': 'docente_publicacion_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteTituloAcademico',
            fields=[
                ('id_titulo', models.BigAutoField(db_column='id_titulo', primary_key=True, serialize=False)),
                ('nombre_titulo', models.CharField(db_column='nombre_titulo', max_length=200)),
                ('nivel_titulo', models.SmallIntegerField(db_column='nivel_titulo')),
                ('fecha_obtencion_titulo', models.DateField(blank=True, db_column='fecha_obtencion_titulo', null=True)),
                ('numero_registro_titulo', models.CharField(blank=True, db_column='numero_registro_titulo', max_length=50, null=True)),
                ('numero_registro_senescyt', models.CharField(blank=True, db_column='numero_registro_senescyt', max_length=50, null=True, unique=True)),
                ('fecha_registro_senescyt', models.DateField(blank=True, db_column='fecha_registro_senescyt', null=True)),
            ],
            options={
                'verbose_name': 'Título Académico (Docente)',
                'verbose_name_plural': 'M2 · Docentes · Títulos Académicos',
                'db_table': 'docente_titulo_academico',
                'managed': False,
            },
        ),
    ]
