from django.urls import path
from . import views

app_name = 'planificacion'

urlpatterns = [
    path('catalogo-actividades/', views.CatalogoActividadComplementariaListView.as_view(), name='catalogoactividadcomplementaria_list'),
    path('catalogo-actividades/crear/', views.CatalogoActividadComplementariaCreateView.as_view(), name='catalogoactividadcomplementaria_create'),
    path('catalogo-actividades/<int:pk>/editar/', views.CatalogoActividadComplementariaUpdateView.as_view(), name='catalogoactividadcomplementaria_update'),
    path('catalogo-actividades/<int:pk>/eliminar/', views.CatalogoActividadComplementariaDeleteView.as_view(), name='catalogoactividadcomplementaria_delete'),
    path('actividades-docentes/', views.PlanificacionActividadDocenteListView.as_view(), name='planificacionactividaddocente_list'),
    path('actividades-docentes/crear/', views.PlanificacionActividadDocenteCreateView.as_view(), name='planificacionactividaddocente_create'),
    path('actividades-docentes/<int:pk>/editar/', views.PlanificacionActividadDocenteUpdateView.as_view(), name='planificacionactividaddocente_update'),
    path('actividades-docentes/<int:pk>/eliminar/', views.PlanificacionActividadDocenteDeleteView.as_view(), name='planificacionactividaddocente_delete'),
    path('demanda/', views.PlanificacionDemandaAcademicaListView.as_view(), name='planificaciondemandaacademica_list'),
    path('demanda/crear/', views.PlanificacionDemandaAcademicaCreateView.as_view(), name='planificaciondemandaacademica_create'),
    path('demanda/<int:pk>/editar/', views.PlanificacionDemandaAcademicaUpdateView.as_view(), name='planificaciondemandaacademica_update'),
    path('demanda/<int:pk>/eliminar/', views.PlanificacionDemandaAcademicaDeleteView.as_view(), name='planificaciondemandaacademica_delete'),
    path('asignaciones/', views.PlanificacionAsignacionDocenteListView.as_view(), name='planificacionasignaciondocente_list'),
    path('asignaciones/crear/', views.PlanificacionAsignacionDocenteCreateView.as_view(), name='planificacionasignaciondocente_create'),
    path('asignaciones/<int:pk>/editar/', views.PlanificacionAsignacionDocenteUpdateView.as_view(), name='planificacionasignaciondocente_update'),
    path('asignaciones/<int:pk>/eliminar/', views.PlanificacionAsignacionDocenteDeleteView.as_view(), name='planificacionasignaciondocente_delete'),
    path('reparto/', views.PlanificacionRepartoHorasListView.as_view(), name='planificacionrepartohoras_list'),
    path('reparto/crear/', views.PlanificacionRepartoHorasCreateView.as_view(), name='planificacionrepartohoras_create'),
    path('reparto/<int:pk>/editar/', views.PlanificacionRepartoHorasUpdateView.as_view(), name='planificacionrepartohoras_update'),
    path('reparto/<int:pk>/eliminar/', views.PlanificacionRepartoHorasDeleteView.as_view(), name='planificacionrepartohoras_delete'),
    path('matriz-f4/', views.PlanificacionMatrizF4ListView.as_view(), name='planificacionmatrizf4_list'),
    path('matriz-f4/crear/', views.PlanificacionMatrizF4CreateView.as_view(), name='planificacionmatrizf4_create'),
    path('matriz-f4/<int:pk>/editar/', views.PlanificacionMatrizF4UpdateView.as_view(), name='planificacionmatrizf4_update'),
    path('matriz-f4/<int:pk>/eliminar/', views.PlanificacionMatrizF4DeleteView.as_view(), name='planificacionmatrizf4_delete'),
    path('aulas/', views.PlanificacionAulaHorarioListView.as_view(), name='planificacionaulahorario_list'),
    path('aulas/crear/', views.PlanificacionAulaHorarioCreateView.as_view(), name='planificacionaulahorario_create'),
    path('aulas/<int:pk>/editar/', views.PlanificacionAulaHorarioUpdateView.as_view(), name='planificacionaulahorario_update'),
    path('aulas/<int:pk>/eliminar/', views.PlanificacionAulaHorarioDeleteView.as_view(), name='planificacionaulahorario_delete'),

    path('horas-docentes/', views.reporte_horas_docentes, name='reporte_horas_docentes'),
    path('operativa/', views.planificacion_operativa, name='planificacion_operativa'),
    path('operativa/asignar/', views.asignar_docente_operativa, name='asignar_docente_operativa'),
    path('consolidado-docentes/', views.planificacion_consolidada_docentes, name='planificacion_consolidada_docentes'),
    path('validacion-excel/', views.validacion_excel_planificacion, name='validacion_excel'),
    path('validacion-excel/sincronizar/', views.sincronizar_excel_planificacion, name='sincronizar_excel'),
    path('asignacion-inteligente/', views.asignacion_inteligente, name='asignacion_inteligente'),
    path('paralelos-matriz/', views.planificacion_paralelos_matriz, name='planificacion_paralelos_matriz'),
    path('api/asignatura-info/', views.api_asignatura_info, name='api_asignatura_info'),
    path('api/recommendations/', views.api_recommendations, name='api_recommendations'),
    path('api/validar-horas/', views.api_validar_horas_disponibles, name='api_validar_horas'),
    path('api/check-affinity/', views.api_check_affinity, name='api_check_affinity'),
    path('api/crear-asignacion/', views.api_crear_asignacion, name='api_crear_asignacion'),
    path('api/paralelos-disponibles/', views.api_paralelos_disponibles, name='api_paralelos_disponibles'),
]
