# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRegistroCambios',
            fields=[
                ('id_registro_auditoria', models.BigAutoField(db_column='id_registro_auditoria', primary_key=True, serialize=False)),
                ('nombre_tabla_afectada', models.CharField(db_column='nombre_tabla_afectada', max_length=60)),
                ('id_registro_afectado', models.BigIntegerField(db_column='id_registro_afectado')),
                ('tipo_accion', models.CharField(db_column='tipo_accion', max_length=10)),
                ('valor_anterior', models.JSONField(blank=True, db_column='valor_anterior', null=True)),
                ('valor_nuevo', models.JSONField(blank=True, db_column='valor_nuevo', null=True)),
                ('fecha_hora_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_cambio')),
                ('direccion_ip_origen', models.CharField(blank=True, db_column='direccion_ip_origen', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'M6 · Auditoría · Registro de Cambios',
                'db_table': 'auditoria_registro_cambios',
                'managed': False,
            },
        ),
    ]
