# Generated by Django 6.0.6 on 2026-06-10 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=200, verbose_name='Nombre de la carrera')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dedicacion', models.CharField(max_length=100, verbose_name='Nombre de dedicación')),
            ],
            options={
                'verbose_name': 'Dedicación',
                'verbose_name_plural': 'Dedicaciones',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cédula')),
                ('apellidos_nombres', models.CharField(max_length=255, verbose_name='Apellidos y nombres')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_licencia', models.CharField(max_length=100, verbose_name='Nombre de licencia')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modalidad', models.CharField(max_length=100, verbose_name='Nombre de modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100, verbose_name='Nombre del país')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de publicación',
                'verbose_name_plural': 'Tipos de publicación',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cédula')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(max_length=100, verbose_name='Nombre del periodo')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='DocenteTransaccional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('adj_archivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo adjunto')),
                ('id_carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrera', verbose_name='Carrera')),
                ('id_dedicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dedicacion', verbose_name='Dedicación')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente', verbose_name='Docente')),
                ('id_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.licencia', verbose_name='Licencia')),
                ('id_modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modalidad', verbose_name='Modalidad')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Docente Transaccional',
                'verbose_name_plural': 'Docentes Transaccionales',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publicacion', models.CharField(max_length=255, verbose_name='Nombre de la publicación')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código')),
                ('funcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Función')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente', verbose_name='Docente')),
                ('id_tipo_publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopublicacion', verbose_name='Tipo de publicación')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('hora_total', models.IntegerField(blank=True, null=True, verbose_name='Horas totales')),
                ('id_tipo_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopublicacion', verbose_name='Tipo de curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del título')),
                ('fecha_titulo', models.DateField(blank=True, null=True, verbose_name='Fecha del título')),
                ('registro_titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro del título')),
                ('fecha_senecyt', models.DateField(blank=True, null=True, verbose_name='Fecha Senescyt')),
                ('registro_senecyt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Senescyt')),
                ('id_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente', verbose_name='Docente')),
                ('id_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
        migrations.CreateModel(
            name='CursoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso', verbose_name='Curso')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Curso - Docente',
                'verbose_name_plural': 'Cursos - Docentes',
                'unique_together': {('id_curso', 'id_docente')},
            },
        ),
    ]
