# Generated by Django 6.0.6 on 2026-06-11 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Este campo debe tener exactamente 10 dígitos numéricos.')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Este campo debe tener exactamente 10 dígitos numéricos.')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Este campo debe tener exactamente 10 dígitos numéricos.')], verbose_name='Cédula'),
        ),
    ]
