# Generated by Django 5.0.14 on 2026-07-22 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_legacy_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Usuario = apps.get_model('core', 'Usuario')
    role_names = ['Administrador', 'Autoridad', 'Coordinador', 'Funcionario', 'Docente']
    groups = {name: Group.objects.get_or_create(name=name)[0] for name in role_names}
    legacy = Group.objects.filter(name='Usuario').first()
    if legacy:
        for user in Usuario.objects.filter(groups=legacy, is_superuser=False):
            user.groups.remove(legacy)
            user.groups.add(groups['Docente'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_carrera_es_actividad'),
        ('core', '0002_alter_docente_cedula_alter_docente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credenciales_emitidas_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='credenciales_emitidas_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciales_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Obliga al usuario a definir una contraseña personal en su próximo acceso.', verbose_name='Debe cambiar la contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_cambiado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREAR_CUENTA', 'Creación de cuenta'), ('EDITAR_CUENTA', 'Edición de cuenta'), ('EMITIR_CLAVE', 'Emisión de contraseña temporal'), ('CAMBIAR_CLAVE', 'Cambio de contraseña'), ('ACTIVAR', 'Activación de cuenta'), ('DESACTIVAR', 'Desactivación de cuenta'), ('LOGIN_FALLIDO', 'Inicio de sesión fallido')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de seguridad',
                'verbose_name_plural': 'Eventos de seguridad',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='UsuarioAlcanceCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('asignado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcances_asignados', to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_autorizados', to='catalogos.catalogocarrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances_carrera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alcance de carrera',
                'verbose_name_plural': 'Alcances de carrera',
            },
        ),
        migrations.AddConstraint(
            model_name='usuarioalcancecarrera',
            constraint=models.UniqueConstraint(fields=('usuario', 'carrera'), name='uq_usuario_alcance_carrera'),
        ),
        migrations.RunPython(normalize_legacy_roles, migrations.RunPython.noop),
    ]
