# Generated by Django 5.0.14 on 2026-07-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_credenciales_emitidas_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentetransaccional',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del documento'),
        ),
    ]
