# Generated by Django 5.2.17 on 2026-08-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_docentetransaccional_fecha_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('modulos', models.JSONField(default=dict, help_text='Formato: {"modulo": ["view", "change"]} o {"*": ["view", "change"]}.', verbose_name='Permisos por módulo')),
                ('alcance', models.CharField(choices=[('global', 'Global (toda la facultad)'), ('carreras', 'Por carrera (Usuarios de carrera)'), ('propio', 'Solo datos propios'), ('ninguno', 'Sin alcance')], default='propio', help_text='global: toda la facultad; carreras: solo las autorizadas; propio: solo datos propios.', max_length=20, verbose_name='Alcance')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('rol_base', models.ForeignKey(blank=True, help_text='Permisos heredados del rol base (p. ej. Decano hereda Docente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_heredados', to='core.rol', verbose_name='Rol base heredado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ('codigo',),
            },
        ),
    ]
