# Generated by Django 5.0.14 on 2026-08-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='rol_base',
        ),
    ]
