# Generated by Django 5.0.14 on 2026-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='asignable_por_admin',
            field=models.BooleanField(default=True, help_text='Roles heredados o de compatibilidad (p. ej. Usuario, Estudiante) se desmarcan para que no aparezcan como opción al crear/editar cuentas.', verbose_name='Asignable desde "Nuevo usuario"/"Editar usuario"'),
        ),
    ]
