# Generated by Django 4.2.30 on 2026-07-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCampoConocimiento',
            fields=[
                ('id_campo', models.AutoField(db_column='id_campo', primary_key=True, serialize=False)),
                ('codigo_campo', models.CharField(db_column='codigo_campo', max_length=20, unique=True)),
                ('nombre_campo_conocimiento', models.CharField(db_column='nombre_campo_conocimiento', max_length=100)),
            ],
            options={
                'verbose_name': '[Catálogo] Campo Conocimiento',
                'verbose_name_plural': 'M1 · Catálogos · Campos Conocimiento',
                'db_table': 'catalogo_campo_conocimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoCarrera',
            fields=[
                ('id_carrera', models.AutoField(db_column='id_carrera', primary_key=True, serialize=False)),
                ('codigo_carrera', models.CharField(db_column='codigo_carrera', max_length=20, unique=True)),
                ('nombre_carrera', models.CharField(db_column='nombre_carrera', max_length=120)),
                ('carrera_activa', models.BooleanField(db_column='carrera_activa', default=True)),
            ],
            options={
                'verbose_name': '[Catálogo] Carrera',
                'verbose_name_plural': 'M1 · Catálogos · Carreras',
                'db_table': 'catalogo_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoDedicacionHoraria',
            fields=[
                ('id_dedicacion', models.AutoField(db_column='id_dedicacion', primary_key=True, serialize=False)),
                ('codigo_dedicacion', models.CharField(db_column='codigo_dedicacion', max_length=5, unique=True)),
                ('nombre_dedicacion', models.CharField(db_column='nombre_dedicacion', max_length=30)),
            ],
            options={
                'verbose_name': '[Catálogo] Dedicación Horaria',
                'verbose_name_plural': 'M1 · Catálogos · Dedicaciones Horarias',
                'db_table': 'catalogo_dedicacion_horaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoGradoAfinidad',
            fields=[
                ('id_grado_afinidad', models.AutoField(db_column='id_grado_afinidad', primary_key=True, serialize=False)),
                ('codigo_grado_afinidad', models.CharField(db_column='codigo_grado_afinidad', max_length=10, unique=True)),
                ('nombre_grado_afinidad', models.CharField(db_column='nombre_grado_afinidad', max_length=50)),
                ('nivel_prioridad', models.SmallIntegerField(db_column='nivel_prioridad')),
            ],
            options={
                'verbose_name': '[Catálogo] Grado Afinidad',
                'verbose_name_plural': 'M1 · Catálogos · Grados Afinidad',
                'db_table': 'catalogo_grado_afinidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoModalidadContratacion',
            fields=[
                ('id_modalidad', models.AutoField(db_column='id_modalidad', primary_key=True, serialize=False)),
                ('codigo_modalidad', models.CharField(db_column='codigo_modalidad', max_length=15, unique=True)),
                ('nombre_modalidad', models.CharField(db_column='nombre_modalidad', max_length=50)),
            ],
            options={
                'verbose_name': '[Catálogo] Modalidad Contratación',
                'verbose_name_plural': 'M1 · Catálogos · Modalidades Contratación',
                'db_table': 'catalogo_modalidad_contratacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoPais',
            fields=[
                ('id_pais', models.AutoField(db_column='id_pais', primary_key=True, serialize=False)),
                ('codigo_iso_pais', models.CharField(db_column='codigo_iso_pais', max_length=2, unique=True)),
                ('nombre_pais', models.CharField(db_column='nombre_pais', max_length=100)),
                ('nombre_nacionalidad', models.CharField(db_column='nombre_nacionalidad', max_length=100)),
            ],
            options={
                'verbose_name': '[Catálogo] País',
                'verbose_name_plural': 'M1 · Catálogos · Países',
                'db_table': 'catalogo_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoPeriodoAcademico',
            fields=[
                ('id_periodo', models.AutoField(db_column='id_periodo', primary_key=True, serialize=False)),
                ('codigo_periodo', models.CharField(db_column='codigo_periodo', max_length=10, unique=True)),
                ('nombre_periodo', models.CharField(db_column='nombre_periodo', max_length=20)),
                ('periodo_activo', models.BooleanField(db_column='periodo_activo', default=False)),
                ('fecha_inicio_periodo', models.DateField(blank=True, db_column='fecha_inicio_periodo', null=True)),
                ('fecha_fin_periodo', models.DateField(blank=True, db_column='fecha_fin_periodo', null=True)),
            ],
            options={
                'verbose_name': '[Catálogo] Período Académico',
                'verbose_name_plural': 'M1 · Catálogos · Períodos Académicos',
                'db_table': 'catalogo_periodo_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoCursoCapacitacion',
            fields=[
                ('id_tipo_curso', models.AutoField(db_column='id_tipo_curso', primary_key=True, serialize=False)),
                ('codigo_tipo_curso', models.CharField(db_column='codigo_tipo_curso', max_length=15, unique=True)),
                ('nombre_tipo_curso', models.CharField(db_column='nombre_tipo_curso', max_length=50)),
            ],
            options={
                'verbose_name': '[Catálogo] Tipo Curso Capacitación',
                'verbose_name_plural': 'M1 · Catálogos · Tipos Curso Capacitación',
                'db_table': 'catalogo_tipo_curso_capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoDocente',
            fields=[
                ('id_tipo_docente', models.AutoField(db_column='id_tipo_docente', primary_key=True, serialize=False)),
                ('codigo_tipo_docente', models.CharField(db_column='codigo_tipo_docente', max_length=15, unique=True)),
                ('nombre_tipo_docente', models.CharField(db_column='nombre_tipo_docente', max_length=30)),
            ],
            options={
                'verbose_name': '[Catálogo] Tipo Docente',
                'verbose_name_plural': 'M1 · Catálogos · Tipos Docente',
                'db_table': 'catalogo_tipo_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoLicencia',
            fields=[
                ('id_licencia', models.AutoField(db_column='id_licencia', primary_key=True, serialize=False)),
                ('codigo_licencia', models.CharField(db_column='codigo_licencia', max_length=15, unique=True)),
                ('nombre_licencia', models.CharField(db_column='nombre_licencia', max_length=50)),
            ],
            options={
                'verbose_name': '[Catálogo] Tipo Licencia',
                'verbose_name_plural': 'M1 · Catálogos · Tipos Licencia',
                'db_table': 'catalogo_tipo_licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoPublicacion',
            fields=[
                ('id_tipo_publicacion', models.AutoField(db_column='id_tipo_publicacion', primary_key=True, serialize=False)),
                ('codigo_tipo_publicacion', models.CharField(db_column='codigo_tipo_publicacion', max_length=15, unique=True)),
                ('nombre_tipo_publicacion', models.CharField(db_column='nombre_tipo_publicacion', max_length=50)),
            ],
            options={
                'verbose_name': '[Catálogo] Tipo Publicación',
                'verbose_name_plural': 'M1 · Catálogos · Tipos Publicación',
                'db_table': 'catalogo_tipo_publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTituloPosgrado',
            fields=[
                ('id_posgrado', models.AutoField(db_column='id_posgrado', primary_key=True, serialize=False)),
                ('codigo_posgrado', models.CharField(db_column='codigo_posgrado', max_length=20, unique=True)),
                ('nombre_titulo_posgrado', models.CharField(db_column='nombre_titulo_posgrado', max_length=200)),
            ],
            options={
                'verbose_name': '[Catálogo] Título Posgrado',
                'verbose_name_plural': 'M1 · Catálogos · Títulos Posgrado',
                'db_table': 'catalogo_titulo_posgrado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionCarreraPeriodo',
            fields=[
                ('id_carrera_periodo', models.AutoField(db_column='id_carrera_periodo', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '[Relación] Carrera × Período',
                'verbose_name_plural': 'M1 · Catálogos · Carreras por Período',
                'db_table': 'relacion_carrera_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimiteHorario',
            fields=[
                ('id_limite', models.AutoField(primary_key=True, serialize=False)),
                ('horas_maximas', models.PositiveSmallIntegerField(verbose_name='Horas máximas de clase')),
                ('horas_complementarias_maximas', models.PositiveSmallIntegerField(default=0, verbose_name='Horas complementarias máximas')),
                ('activo', models.BooleanField(default=True)),
                ('id_dedicacion', models.ForeignKey(db_column='id_dedicacion', on_delete=django.db.models.deletion.CASCADE, to='catalogos.catalogodedicacionhoraria')),
            ],
            options={
                'verbose_name': 'Límite Horario',
                'verbose_name_plural': 'M1 · Catálogos · Límites Horarios',
                'db_table': 'limite_horario',
                'managed': True,
                'unique_together': {('id_dedicacion',)},
            },
        ),
    ]
