# Generated by Django 5.0.14 on 2026-07-31 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_periodo_estado_planificacion'),
        ('certificados', '0002_firma_manual_sello_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoemitido',
            name='id_periodo',
            field=models.ForeignKey(blank=True, db_column='id_periodo', help_text='Dejar vacío para incluir todo el historial disponible.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to='catalogos.catalogoperiodoacademico', verbose_name='Período académico'),
        ),
    ]
