# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionAsignacionDocente',
            fields=[
                ('id_asignacion', models.BigAutoField(db_column='id_asignacion', primary_key=True, serialize=False)),
                ('nivel_semestre_asignado', models.SmallIntegerField(db_column='nivel_semestre_asignado')),
                ('paralelo_asignado', models.CharField(db_column='paralelo_asignado', max_length=3)),
                ('horas_clase', models.SmallIntegerField(db_column='horas_clase', default=0)),
                ('horas_complementarias', models.SmallIntegerField(db_column='horas_complementarias', default=0)),
                ('comision_servicio', models.CharField(blank=True, db_column='comision_servicio', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Asignación Docente (Planificación)',
                'verbose_name_plural': 'M5 · Planificación · Asignación Docente',
                'db_table': 'planificacion_asignacion_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanificacionAulaHorario',
            fields=[
                ('id_horario', models.AutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(db_column='nombre_aula', max_length=50)),
                ('turno_horario', models.CharField(db_column='turno_horario', max_length=10)),
                ('nivel_asignado', models.CharField(blank=True, db_column='nivel_asignado', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Aula / Horario',
                'verbose_name_plural': 'M5 · Planificación · Aulas y Horarios',
                'db_table': 'planificacion_aula_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanificacionDemandaAcademica',
            fields=[
                ('id_demanda', models.BigAutoField(db_column='id_demanda', primary_key=True, serialize=False)),
                ('proyeccion_estudiantes', models.IntegerField(db_column='proyeccion_estudiantes', default=0)),
                ('numero_paralelos', models.SmallIntegerField(db_column='numero_paralelos', default=1)),
            ],
            options={
                'verbose_name': 'Demanda Académica',
                'verbose_name_plural': 'M5 · Planificación · Demanda Académica',
                'db_table': 'planificacion_demanda_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanificacionMatrizF4',
            fields=[
                ('id_registro_f4', models.BigAutoField(db_column='id_registro_f4', primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(db_column='tipo_actividad', max_length=100)),
                ('nombre_asignatura_actividad', models.CharField(blank=True, db_column='nombre_asignatura_actividad', max_length=200, null=True)),
                ('nivel_semestre_actividad', models.CharField(blank=True, db_column='nivel_semestre_actividad', max_length=20, null=True)),
                ('horas_actividad', models.SmallIntegerField(db_column='horas_actividad', default=0)),
                ('numero_paralelos_actividad', models.SmallIntegerField(db_column='numero_paralelos_actividad', default=1)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
            ],
            options={
                'verbose_name': 'Matriz F4',
                'verbose_name_plural': 'M5 · Planificación · Matriz F4',
                'db_table': 'planificacion_matriz_f4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanificacionRepartoHoras',
            fields=[
                ('id_reparto', models.BigAutoField(db_column='id_reparto', primary_key=True, serialize=False)),
                ('nivel_paralelo', models.CharField(db_column='nivel_paralelo', max_length=5)),
                ('horas_presenciales_asignadas', models.SmallIntegerField(db_column='horas_presenciales_asignadas', default=0)),
            ],
            options={
                'verbose_name': 'Reparto de Horas',
                'verbose_name_plural': 'M5 · Planificación · Reparto de Horas',
                'db_table': 'planificacion_reparto_horas',
                'managed': False,
            },
        ),
    ]
