# Generated by Django 5.0.14 on 2026-07-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_capacidad_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionCapacidadEspecial',
            fields=[
                ('id_capacidad', models.BigAutoField(db_column='id_capacidad', primary_key=True, serialize=False)),
                ('estudiante_nombre', models.CharField(db_column='estudiante_nombre', max_length=200)),
                ('condicion', models.CharField(blank=True, db_column='condicion', max_length=200, null=True)),
                ('informes_adjuntos', models.TextField(blank=True, db_column='informes_adjuntos', null=True)),
                ('nivel_asignado', models.CharField(blank=True, db_column='nivel_asignado', max_length=10, null=True)),
                ('paralelo_asignado', models.CharField(blank=True, db_column='paralelo_asignado', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Capacidad Especial',
                'verbose_name_plural': 'M5 · Planificación · Capacidades Especiales',
                'db_table': 'planificacion_capacidad_especial',
                'managed': False,
            },
        ),
    ]
