# Generated by Django 5.0.14 on 2026-07-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_validacion_tipo_documento'),
        ('planificacion', '0010_planificacioncapacidadespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraUsoLaboratorio',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('semana', models.PositiveSmallIntegerField()),
                ('fecha_uso', models.DateField()),
                ('tipo_espacio', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('CENTRO_COMPUTO', 'Centro de cómputo')], max_length=20)),
                ('nombre_espacio', models.CharField(max_length=100)),
                ('horas_uso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('actividad_realizada', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_actividad_docente', models.ForeignKey(blank=True, db_column='id_actividad_docente', null=True, on_delete=django.db.models.deletion.RESTRICT, to='planificacion.planificacionactividaddocente')),
                ('id_asignacion', models.ForeignKey(blank=True, db_column='id_asignacion', null=True, on_delete=django.db.models.deletion.RESTRICT, to='planificacion.planificacionasignaciondocente')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.RESTRICT, to='docentes.docentefcacc')),
            ],
            options={
                'verbose_name': 'Registro de uso de laboratorio',
                'verbose_name_plural': 'Bitácora de laboratorios y centros de cómputo',
                'db_table': 'bitacora_uso_laboratorio',
                'ordering': ('-fecha_uso', '-id_bitacora'),
            },
        ),
        migrations.AddConstraint(
            model_name='bitacorausolaboratorio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('id_asignacion__isnull', False), ('id_actividad_docente__isnull', True)), models.Q(('id_asignacion__isnull', True), ('id_actividad_docente__isnull', False)), _connector='OR'), name='chk_bitacora_un_origen'),
        ),
        migrations.AddConstraint(
            model_name='bitacorausolaboratorio',
            constraint=models.CheckConstraint(check=models.Q(('semana__gte', 1)), name='chk_bitacora_semana_positiva'),
        ),
        migrations.AddConstraint(
            model_name='bitacorausolaboratorio',
            constraint=models.CheckConstraint(check=models.Q(('horas_uso__gt', 0)), name='chk_bitacora_horas_positivas'),
        ),
    ]
