# Generated by Django 5.0.14 on 2026-07-28 14:58

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_spaces(apps, schema_editor):
    Space = apps.get_model('planificacion', 'CatalogoEspacioAcademico')
    Log = apps.get_model('planificacion', 'BitacoraUsoLaboratorio')
    legacy = Log.objects.filter(id_espacio__isnull=True).values(
        'tipo_espacio', 'nombre_espacio'
    ).distinct()
    for index, item in enumerate(legacy, start=1):
        space = Space.objects.create(
            codigo_espacio=f'LEGACY-{index:04d}',
            nombre_espacio=item['nombre_espacio'],
            tipo_espacio=item['tipo_espacio'],
        )
        Log.objects.filter(
            id_espacio__isnull=True,
            tipo_espacio=item['tipo_espacio'],
            nombre_espacio=item['nombre_espacio'],
        ).update(id_espacio=space)


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_bitacorausolaboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEspacioAcademico',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_espacio', models.CharField(max_length=20, unique=True)),
                ('nombre_espacio', models.CharField(max_length=100)),
                ('tipo_espacio', models.CharField(choices=[('AULA', 'Aula de clases'), ('LABORATORIO', 'Laboratorio'), ('CENTRO_COMPUTO', 'Centro de cómputo')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('capacidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('espacio_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espacio académico',
                'verbose_name_plural': 'Catálogo de aulas, laboratorios y centros de cómputo',
                'db_table': 'catalogo_espacio_academico',
                'ordering': ('tipo_espacio', 'nombre_espacio'),
            },
        ),
        migrations.AlterField(
            model_name='bitacorausolaboratorio',
            name='tipo_espacio',
            field=models.CharField(choices=[('AULA', 'Aula de clases'), ('LABORATORIO', 'Laboratorio'), ('CENTRO_COMPUTO', 'Centro de cómputo')], max_length=20),
        ),
        migrations.AddField(
            model_name='bitacorausolaboratorio',
            name='id_espacio',
            field=models.ForeignKey(blank=True, db_column='id_espacio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='planificacion.catalogoespacioacademico'),
        ),
        migrations.RunPython(
            migrate_legacy_spaces,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
