# Generated by Django 5.0.14 on 2026-07-28 15:09

from django.db import migrations, models


def unify_computer_centers(apps, schema_editor):
    Space = apps.get_model('planificacion', 'CatalogoEspacioAcademico')
    Log = apps.get_model('planificacion', 'BitacoraUsoLaboratorio')
    Space.objects.filter(tipo_espacio='LABORATORIO').update(
        tipo_espacio='CENTRO_COMPUTO'
    )
    Log.objects.filter(tipo_espacio='LABORATORIO').update(
        tipo_espacio='CENTRO_COMPUTO'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_catalogoespacioacademico_and_more'),
    ]

    operations = [
        migrations.RunPython(
            unify_computer_centers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='bitacorausolaboratorio',
            options={'ordering': ('-fecha_uso', '-id_bitacora'), 'verbose_name': 'Registro de uso de centro de cómputo', 'verbose_name_plural': 'Bitácora de centros de cómputo'},
        ),
        migrations.AlterModelOptions(
            name='catalogoespacioacademico',
            options={'ordering': ('tipo_espacio', 'nombre_espacio'), 'verbose_name': 'Espacio académico', 'verbose_name_plural': 'Catálogo de aulas y centros de cómputo'},
        ),
        migrations.AlterField(
            model_name='bitacorausolaboratorio',
            name='tipo_espacio',
            field=models.CharField(choices=[('AULA', 'Aula de clases'), ('CENTRO_COMPUTO', 'Centro de cómputo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogoespacioacademico',
            name='tipo_espacio',
            field=models.CharField(choices=[('AULA', 'Aula de clases'), ('CENTRO_COMPUTO', 'Centro de cómputo')], max_length=20),
        ),
    ]
