# Generated by Django 5.2.17 on 2026-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0013_alter_bitacorausolaboratorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoactividadcomplementaria',
            name='peso',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Incluir (se toma en cuenta)'), (0, '0 - Excluir (no se imprime)')], default=1, verbose_name='Peso para informes (1 = se imprime, 0 = se excluye)'),
        ),
    ]
