# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadRol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('codigo_rol', models.CharField(db_column='codigo_rol', max_length=15, unique=True)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=50)),
                ('descripcion_rol', models.CharField(blank=True, db_column='descripcion_rol', max_length=200, null=True)),
                ('rol_activo', models.BooleanField(db_column='rol_activo', default=True)),
            ],
            options={
                'verbose_name': 'Rol de Seguridad',
                'verbose_name_plural': 'M3 · Seguridad · Roles',
                'db_table': 'seguridad_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguridadUsuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(db_column='contrasena_hash', max_length=255)),
                ('usuario_activo', models.BooleanField(db_column='usuario_activo', default=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, db_column='fecha_ultimo_acceso', null=True)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion_usuario')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'M3 · Seguridad · Usuarios',
                'db_table': 'seguridad_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguridadUsuarioRol',
            fields=[
                ('id_usuario_rol', models.BigAutoField(db_column='id_usuario_rol', primary_key=True, serialize=False)),
                ('fecha_asignacion_rol', models.DateField(db_column='fecha_asignacion_rol')),
            ],
            options={
                'verbose_name': 'Asignación Usuario × Rol × Carrera',
                'verbose_name_plural': 'M3 · Seguridad · Usuarios Roles',
                'db_table': 'seguridad_usuario_rol',
                'managed': False,
            },
        ),
    ]
