# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id_cabecera', models.AutoField(db_column='id_cabecera', primary_key=True, serialize=False)),
                ('descripcion_periodo', models.CharField(db_column='descripcion_periodo', max_length=100)),
            ],
            options={
                'verbose_name': 'Cabecera de Planificación',
                'verbose_name_plural': 'M7 · Planif. Complementaria · Cabeceras',
                'db_table': 'cabecera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id_cuerpo', models.BigAutoField(db_column='id_cuerpo', primary_key=True, serialize=False)),
                ('horas', models.IntegerField(db_column='horas')),
            ],
            options={
                'verbose_name': 'Detalle de Horas (Cuerpo)',
                'verbose_name_plural': 'M7 · Planif. Complementaria · Detalle Horas',
                'db_table': 'cuerpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialLimitacion',
            fields=[
                ('id_historial', models.BigAutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('fecha_inicio_vigencia', models.DateField(db_column='fecha_inicio_vigencia')),
                ('fecha_fin_vigencia', models.DateField(db_column='fecha_fin_vigencia')),
            ],
            options={
                'verbose_name': 'Historial de Limitación',
                'verbose_name_plural': 'M7 · Limitaciones · Historial',
                'db_table': 'historial_limitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Limitacion',
            fields=[
                ('id_limitacion', models.AutoField(db_column='id_limitacion', primary_key=True, serialize=False)),
                ('codigo_limitacion', models.CharField(db_column='codigo_limitacion', max_length=15, unique=True)),
                ('nombre_limitacion', models.CharField(db_column='nombre_limitacion', max_length=150)),
                ('hora_minima', models.IntegerField(db_column='hora_minima')),
                ('hora_maxima', models.IntegerField(db_column='hora_maxima')),
            ],
            options={
                'verbose_name': 'Límite / Regla',
                'verbose_name_plural': 'M7 · Limitaciones · Reglas',
                'db_table': 'limitacion',
                'managed': False,
            },
        ),
    ]
