# Generated by Django 5.0.14 on 2026-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculoAsignatura',
            fields=[
                ('id_asignatura', models.AutoField(db_column='id_asignatura', primary_key=True, serialize=False)),
                ('codigo_asignatura', models.CharField(db_column='codigo_asignatura', max_length=20, unique=True)),
                ('nombre_asignatura', models.CharField(db_column='nombre_asignatura', max_length=200)),
                ('horas_semanales_asignatura', models.SmallIntegerField(db_column='horas_semanales_asignatura', default=0)),
                ('nivel_semestre', models.SmallIntegerField(db_column='nivel_semestre')),
            ],
            options={
                'verbose_name': 'Asignatura (Currículo)',
                'verbose_name_plural': 'M4 · Currículo · Asignaturas',
                'db_table': 'curriculo_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculoAsignaturaCampo',
            fields=[
                ('id_asignatura_campo', models.AutoField(db_column='id_asignatura_campo', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Asignatura × Campo Conocimiento',
                'verbose_name_plural': 'M4 · Currículo · Asignaturas por Campo',
                'db_table': 'curriculo_asignatura_campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionPosgradoCampo',
            fields=[
                ('id_posgrado_campo', models.AutoField(db_column='id_posgrado_campo', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Posgrado × Campo Conocimiento',
                'verbose_name_plural': 'M4 · Currículo · Posgrados por Campo',
                'db_table': 'relacion_posgrado_campo',
                'managed': False,
            },
        ),
    ]
